# Generated by Django 4.2.6 on 2023-12-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_tool', '0002_boundingbox_category_fileupload_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
