# Generated by Django 4.2.6 on 2023-12-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_tool', '0003_alter_photo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
