# Generated by Django 4.2.6 on 2023-12-12 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_tool', '0006_labellist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoundingBox',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
