# Generated by Django 4.2.6 on 2023-12-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_tool', '0009_labellist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labellist',
            name='color',
        ),
        migrations.RemoveField(
            model_name='labellist',
            name='name',
        ),
        migrations.AddField(
            model_name='labellist',
            name='labelinfo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
