# Generated by Django 4.2.6 on 2023-12-20 08:50

from django.db import migrations, models
import labeling_tool.models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling_tool', '0011_alter_labellist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=labeling_tool.models.user_directory_path),
        ),
    ]
